language: python
python:
  - "3.6"
install:
  - pip install -r tests/test_requirements.txt
script:
  - pytest --cov=pyriad/ --cov-report xml
after_success:
    - python-codacy-coverage -r coverage.xml
